import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import AppProvider from "@/components/providers/app-providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    afterSignOutUrl={"/sign-in"}
    appearance={{
      elements: {
        formButtonPrimary: "bg-primary hover:bg-primary/70 text-sm !shadow-none",
      }
    }}>
      <html lang="en">
        <body className={inter.className}>
          <AppProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </AppProvider>
          <Toaster richColors/>
        </body>
      </html>
    </ClerkProvider>
  );
}
